/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
	light: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(0, 0%, 14.5%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(0, 0%, 14.5%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(0, 0%, 14.5%)",
		primary: "hsl(0, 0%, 20.5%)",
		primaryForeground: "hsl(0, 0%, 98.5%)",
		secondary: "hsl(0, 0%, 97%)",
		secondaryForeground: "hsl(0, 0%, 20.5%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 55.6%)",
		accent: "hsl(0, 0%, 97%)",
		accentForeground: "hsl(0, 0%, 20.5%)",
		destructive: "hsl(0, 80%, 57.7%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 92.2%)",
		input: "hsl(0, 0%, 92.2%)",
		ring: "hsl(0, 0%, 70.8%)",
	},
	dark: {
		background: "hsl(240, 10%, 3.9%)",
		foreground: "hsl(0, 0%, 98%)",
		card: "hsl(240, 10%, 3.9%)",
		cardForeground: "hsl(0, 0%, 98%)",
		popover: "hsl(240, 10%, 3.9%)",
		popoverForeground: "hsl(0, 0%, 98%)",
		primary: "hsl(0, 0%, 98%)",
		primaryForeground: "hsl(240, 5.9%, 10%)",
		secondary: "hsl(240, 3.7%, 15.9%)",
		secondaryForeground: "hsl(0, 0%, 98%)",
		muted: "hsl(240, 3.7%, 15.9%)",
		mutedForeground: "hsl(240, 5%, 64.9%)",
		accent: "hsl(240, 3.7%, 15.9%)",
		accentForeground: "hsl(0, 0%, 98%)",
		destructive: "hsl(0, 62.8%, 30.6%)",
		destructiveForeground: "hsl(0, 85.7%, 97.3%)",
		border: "hsl(240, 3.7%, 15.9%)",
		input: "hsl(240, 3.7%, 15.9%)",
		ring: "hsl(240, 4.9%, 83.9%)",
	},
};
