/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
	light: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(0, 0%, 14.5%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(0, 0%, 14.5%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(0, 0%, 14.5%)",
		primary: "hsl(344, 100%, 65%)",
		primaryForeground: "hsl(0, 0%, 100%)",
		secondary: "hsl(0, 0%, 97%)",
		secondaryForeground: "hsl(0, 0%, 20.5%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 55.6%)",
		accent: "hsl(0, 0%, 97%)",
		accentForeground: "hsl(0, 0%, 20.5%)",
		destructive: "hsl(0, 80%, 57.7%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 92.2%)",
		input: "hsl(0, 0%, 92.2%)",
		ring: "hsl(0, 0%, 70.8%)",
	},
	dark: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(0, 0%, 14.5%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(0, 0%, 14.5%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(0, 0%, 14.5%)",
		primary: "hsl(344, 100%, 76%)",
		primaryForeground: "hsl(0, 0%, 100%)",
		secondary: "hsl(0, 0%, 97%)",
		secondaryForeground: "hsl(0, 0%, 20.5%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 55.6%)",
		accent: "hsl(0, 0%, 97%)",
		accentForeground: "hsl(0, 0%, 20.5%)",
		destructive: "hsl(0, 80%, 57.7%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 92.2%)",
		input: "hsl(0, 0%, 92.2%)",
		ring: "hsl(0, 0%, 70.8%)",
	},
};
